name: AllergyLab CI

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout source
      - name: Checkout source
        uses: actions/checkout@v4

      # Build Docker images
      - name: Build images
        run: |
          cd Part7a
          docker build -t cloud255/al-app:latest ./app
          docker build -t cloud255/al-db-loader:latest ./db-loader
          docker build -t cloud255/al-email:latest ./email

      # Log in to Docker Hub using GitHub secret
      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: cloud255
          password: ${{ secrets.DOCKER_TOKEN }}

      # Push images to Docker Hub
      - name: Push images to DockerHub
        run: |
          docker push cloud255/al-app:latest
          docker push cloud255/al-db-loader:latest
          docker push cloud255/al-email:latest

      # Install cosign
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'   # pick a stable release

      # Verify image signature with cosign
      - name: Verify Docker image signature
        run: |
          cosign verify \
            --certificate-identity "https://github.com/Prince0206/allergylab/.github/workflows/docker.yml@refs/heads/main" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            docker.io/cloud255/al-app:latest